import React from 'react';
import { 
  GraduationCap, Globe, Brain, Database, Zap, BookOpen, 
  Target, Calculator, Award, Info, FileText, CheckCircle2,
  ShieldCheck, Sparkles, AlertCircle, FileCheck, ExternalLink, Layers,
  Activity, Music, Palette, Wrench, Scale, Atom, Code, FlaskConical,
  Dna, History, BookMarked, Languages, Users, HeartHandshake, Lightbulb,
  Compass, Moon, Scroll, Sun, MessageSquare, Feather, Landmark, Flag,
  MapPin, Newspaper, Megaphone, Library, Building2, Briefcase, Receipt,
  DollarSign, BarChart3, Sliders, Gavel, Search, Microscope, Leaf, Map,
  Droplets, CloudRain, TreePine, Mountain, Orbit, Binary, Cog, Radio,
  Flame, Thermometer, Power, Cpu, Bot, Hammer, Truck, Plane, Navigation,
  Rocket, Fuel, Anchor, Utensils, Scissors, Droplet, Factory, Pill,
  PenTool, HardHat, Boxes, Network, Waves, CheckSquare, Sprout, Fish,
  Stethoscope, HeartPulse, Syringe, Coffee, Car, Package, TrendingUp
} from 'lucide-react';

export const getSpecialtyIconByCode = (code: string, className = 'w-6 h-6'): React.ReactElement => {
  const iconMap: Record<string, React.ReactElement> = {
    M001: <GraduationCap className={className} />,
    M002: <HeartHandshake className={className} />,
    M003: <BookOpen className={className} />,
    M004: <ShieldCheck className={className} />,
    M005: <Activity className={className} />,
    M006: <Music className={className} />,
    M007: <Palette className={className} />,
    M008: <Wrench className={className} />,
    M009: <Scale className={className} />,
    M010: <Calculator className={className} />,
    M011: <Atom className={className} />,
    M012: <Code className={className} />,
    M013: <FlaskConical className={className} />,
    M014: <Dna className={className} />,
    M015: <Globe className={className} />,
    M016: <History className={className} />,
    M017: <BookMarked className={className} />,
    M018: <FileText className={className} />,
    M019: <Languages className={className} />,
    M020: <Users className={className} />,
    M021: <HeartHandshake className={className} />,
    M050: <Lightbulb className={className} />,
    M051: <Compass className={className} />,
    M052: <Moon className={className} />,
    M053: <History className={className} />,
    M054: <Scroll className={className} />,
    M055: <Sun className={className} />,
    M056: <MessageSquare className={className} />,
    M057: <Languages className={className} />,
    M058: <Feather className={className} />,
    M059: <Globe className={className} />,
    M060: <BookMarked className={className} />,
    M061: <Users className={className} />,
    M062: <Sparkles className={className} />,
    M063: <Landmark className={className} />,
    M064: <Flag className={className} />,
    M065: <MapPin className={className} />,
    M066: <Brain className={className} />,
    M067: <Newspaper className={className} />,
    M068: <Megaphone className={className} />,
    M069: <Library className={className} />,
    M070: <TrendingUp className={className} />,
    M071: <Building2 className={className} />,
    M072: <Briefcase className={className} />,
    M073: <Receipt className={className} />,
    M074: <DollarSign className={className} />,
    M075: <BarChart3 className={className} />,
    M076: <Sliders className={className} />,
    M077: <Target className={className} />,
    M078: <Gavel className={className} />,
    M079: <Search className={className} />,
    M080: <Dna className={className} />,
    M081: <Microscope className={className} />,
    M082: <FlaskConical className={className} />,
    M083: <Leaf className={className} />,
    M084: <Map className={className} />,
    M085: <Droplets className={className} />,
    M086: <CloudRain className={className} />,
    M087: <TreePine className={className} />,
    M088: <Mountain className={className} />,
    M089: <FlaskConical className={className} />,
    M090: <Orbit className={className} />,
    M091: <Activity className={className} />,
    M092: <Binary className={className} />,
    M093: <Cog className={className} />,
    M094: <Zap className={className} />,
    M095: <ShieldCheck className={className} />,
    M096: <Radio className={className} />,
    M097: <Flame className={className} />,
    M098: <Thermometer className={className} />,
    M099: <Power className={className} />,
    M100: <Cpu className={className} />,
    M101: <Layers className={className} />,
    M102: <Bot className={className} />,
    M103: <Hammer className={className} />,
    M104: <Truck className={className} />,
    M105: <Plane className={className} />,
    M106: <Navigation className={className} />,
    M107: <Rocket className={className} />,
    M108: <Sparkles className={className} />,
    M109: <Fuel className={className} />,
    M110: <Anchor className={className} />,
    M111: <Utensils className={className} />,
    M112: <TreePine className={className} />,
    M113: <Hammer className={className} />,
    M114: <Scissors className={className} />,
    M115: <Droplet className={className} />,
    M116: <Mountain className={className} />,
    M117: <Factory className={className} />,
    M118: <Sparkles className={className} />,
    M119: <Pill className={className} />,
    M120: <Compass className={className} />,
    M121: <Layers className={className} />,
    M122: <PenTool className={className} />,
    M123: <MapPin className={className} />,
    M124: <HardHat className={className} />,
    M125: <Boxes className={className} />,
    M126: <Truck className={className} />,
    M127: <Network className={className} />,
    M128: <Globe className={className} />,
    M129: <Waves className={className} />,
    M130: <CheckSquare className={className} />,
    M131: <Sprout className={className} />,
    M132: <HeartHandshake className={className} />,
    M133: <TreePine className={className} />,
    M134: <Fish className={className} />,
    M135: <Power className={className} />,
    M136: <Wrench className={className} />,
    M137: <Droplets className={className} />,
    M138: <Stethoscope className={className} />,
    M139: <HeartPulse className={className} />,
    M140: <Activity className={className} />,
    M141: <Stethoscope className={className} />,
    M142: <Syringe className={className} />,
    M143: <Dna className={className} />,
    M144: <Stethoscope className={className} />,
    M145: <ShieldCheck className={className} />,
    M146: <Users className={className} />,
    M147: <Compass className={className} />,
    M148: <Sparkles className={className} />,
    M149: <Coffee className={className} />,
    M150: <ShieldCheck className={className} />,
    M151: <Car className={className} />,
    M152: <Package className={className} />,
    M153: <History className={className} />,
    M210: <Network className={className} />,
    M310: <Building2 className={className} />
  };

  return iconMap[code] || <GraduationCap className={className} />;
};
